name = "forge-training"
main = "src/index.js"
compatibility_date = "2026-09-08"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "forge-payments"
database_id = "34c7eade-243d-45bf-a1e4-ee8ba8f409f0"

[ai]
binding = "AI"
